Repository ponyNYC/bridge_2022, pull requests merged in 2022-05, with the labels that each got.

#1 add python decouple to requirements.txt
  bridge/bridge/settings.py
  requirements.txt
Labels: enhancement

#8 added team names to readme
  README.md
Labels: good first issue

#15 Complete Create a New Thread page without styling and pending url for redirection.
  .vscode/settings.json
  bridge/bridge/urls.py
  bridge/bridgeapp/forms.py
  bridge/bridgeapp/static/image/bridge.png
  bridge/bridgeapp/static/styles.css
  bridge/bridgeapp/static/stylesheet.css
  bridge/bridgeapp/templates/new_thread.html
  bridge/bridgeapp/urls.py
  bridge/bridgeapp/views.py
Labels: enhancement

#21 Refactor logics to reduce app size to 3 models/routes/views/templates
  bridge/bridge/urls.py
  bridge/bridgeapp/admin.py
  bridge/bridgeapp/forms.py
  bridge/bridgeapp/migrations/0004_remove_category_slug.py
  bridge/bridgeapp/models.py
  bridge/bridgeapp/static/images/bridge.png
  bridge/bridgeapp/static/styles.css
  bridge/bridgeapp/templates/categories.html
  bridge/bridgeapp/templates/category.html
  bridge/bridgeapp/templates/home.html
  bridge/bridgeapp/templates/new_thread.html
  bridge/bridgeapp/templates/response.html
  bridge/bridgeapp/templates/thread.html
  bridge/bridgeapp/templates/update.html
  bridge/bridgeapp/urls.py
  bridge/bridgeapp/views.py
Labels: enhancement

#24 Temporary backend fix for app crash due to form validation failure
  bridge/bridgeapp/views.py
Labels: bug

#31 Amend--fix default form behavior and template layout
  bridge/bridgeapp/forms.py
  bridge/bridgeapp/templates/category.html
  bridge/bridgeapp/views.py
Labels: enhancement

#34 Edited README to complete usage instructions and include assets that makes it stand out
  README.md
  assets/bryan_button.svg
  assets/chung_button.svg
  assets/django_badge.svg
  assets/jtc_site_screenshot.png
  assets/license_badge.svg
  assets/python_badge.svg
  assets/richard_button.svg
  assets/tony_button.png
Labels: enhancement
